name: Snake animation

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user: 'MdSaifulIslamRafsan'  # Replace with your GitHub username
          svg: true  # Generate SVG file
          gif: false  # Set to true if you want a gif instead
